name: Commits

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint-commits:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    name: Validate Commits

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Clean and Verbose Install Dependencies
        run: |
          echo "--- Forcing a clean install ---"
          rm -rf node_modules
          npm cache clean --force
          npm install --verbose
      
      - name: Verify Plugin Installation
        run: |
          echo "--- Verifying the plugin files exist on disk ---"
          # This command will list the contents of the plugin directory.
          # If it fails with "No such file or directory", we've found the problem.
          ls -lR ${{ github.workspace }}/node_modules/@mridang/commitlint-plugin-conditionals
          echo "------------------------------------------------"



      - name: Inspect Commits
        uses: mridang/action-commit-lint@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
