name: Commits

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint-commits:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    name: Validate Commits

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'

      - name: Install Tool
        run: |
          npm install --global $(jq -r '[ (if (.extends|type) == "array" then .extends[] else .extends end)?, (.plugins[]? | if type == "string" then . else (.[0]? // "") end)? ] | map(select(. != null and . != "" and . != "null")) | unique | .[]' .commitlintrc.json | tr '\n' ' ')

      - name: Print NODE_PATH
        run: echo "NODE_PATH is $(npm root -g)"

      - name: List global packages
        run: npm ls -g --depth=0

      - name: Inspect Commits
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
        with:
          configFile: .commitlintrc.json
        env:
          NODE_PATH: $(npm root -g)
