name: Commits

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  lint-commits:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    name: Validate Commits

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'

      - name: Inspect Commits
        uses: mridang/action-commit-lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
