name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    name: Dummy Job for PR and Main Branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log Message
        run: echo "This is a dummy job running on both PRs and pushes to the main branch."

